name: Testing action
on:
  workflow_dispatch:
  # Run once a month
  # schedule:
  #   - cron: "0 0 1 * *"
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    strategy:
      matrix:
        conference: ["CAV", "ETAPS", "PACMPL", "PLDI", "POPL", "SPLASH"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - run: ./scripts/setup.sh
    - run: ./scripts/conf/conf_all.sh ${{ matrix.conference }}
    - run: ./scripts/util/commit.sh ${{ matrix.conference }}
