name: Testing action
on:
  workflow_dispatch:
  # Run once a month
  # schedule:
  #   - cron: "0 0 1 * *"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8

    - run: ./scripts/setup.sh

    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.19

    - run: ./scripts/conf.sh CAV
